language: node_js
node_js:
  - "8"
  
services:
  - postgresql
  
before_install:
  - cd ~
  - git clone https://github.com/ACWI-SSWD/nldi-db.git
  - wget https://cida.usgs.gov/artifactory/nldi/datasets/nhdplus.yahara.pgdump.gz
  - mkdir ~/liquibase
  - cd ~/liquibase
  - wget https://github.com/liquibase/liquibase/releases/download/liquibase-parent-3.4.2/liquibase-3.4.2-bin.tar.gz
  - tar -xzf liquibase-3.4.2-bin.tar.gz -C ./
  - cd ~/liquibase/lib
  - wget https://jdbc.postgresql.org/download/postgresql-9.4-1204.jdbc42.jar
  
before_script:
  - psql -c 'create database components;' -U postgres
  - psql -c 'create database test;' -U postgres
  - ~/liquibase/liquibase --driver=org.postgresql.Driver --url=jdbc:postgresql://127.0.0.1:5432/components --username=postgres --password= --changeLogFile=./db.changelog.xml update
  - ~/liquibase/liquibase --driver=org.postgresql.Driver --url=jdbc:postgresql://127.0.0.1:5432/test --username=postgres --password= --changeLogFile=./db.changelog.xml update
